const servicesDB = [
    {
        id : 1,
        service : "Car Wraping & Coustomization",
        category : "carwrap",
        imgUrl : "/image/scar.png",
        description : "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Adipiscing commodo elit at imperdiet dui accumsan. Velit euismod in pellentesque massa placerat. Mauris vitae ultricies leo integer malesuada nunc vel risus. Dolor sit amet consectetur adipiscing.",
        link1 : "",
        link2 : "",
        gImg1 : "/image/scar.png", 
        gImg2 : "/image/scar.png", 
        gImg3 : "/image/scar.png", 
        gImg4 : "/image/scar.png", 

    },
    {
        id : 2,
        service : "Bike Wraping & Coustomization",
        category : "bikewrap",
        imgUrl : "/image/sbike.png",
        description : "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Adipiscing commodo elit at imperdiet dui accumsan. Velit euismod in pellentesque massa placerat. Mauris vitae ultricies leo integer malesuada nunc vel risus. Dolor sit amet consectetur adipiscing.",
        link1 : "",
        link2 : "",
        gImg1 : "/image/scar.png", 
        gImg2 : "/image/scar.png", 
        gImg3 : "/image/scar.png", 
        gImg4 : "/image/scar.png", 

    },
    {
        id : 3,
        service : "Car Wraping & Coustomization",
        category : "carwrap",
        imgUrl : "/image/shelmet.png",
        description : "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Adipiscing commodo elit at imperdiet dui accumsan. Velit euismod in pellentesque massa placerat. Mauris vitae ultricies leo integer malesuada nunc vel risus. Dolor sit amet consectetur adipiscing.",
        link1 : "",
        link2 : "",
        gImg1 : "/image/scar.png", 
        gImg2 : "/image/scar.png", 
        gImg3 : "/image/scar.png", 
        gImg4 : "/image/scar.png", 

    },
    {
        id : 4,
        service : "Car Wraping & Coustomization",
        category : "carwrap",
        imgUrl : "/image/smobile.png",
        description : "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Adipiscing commodo elit at imperdiet dui accumsan. Velit euismod in pellentesque massa placerat. Mauris vitae ultricies leo integer malesuada nunc vel risus. Dolor sit amet consectetur adipiscing.",
        link1 : "",
        link2 : "",
        gImg1 : "/image/scar.png", 
        gImg2 : "/image/scar.png", 
        gImg3 : "/image/scar.png", 
        gImg4 : "/image/scar.png", 

    },
    {
        id : 5,
        service : "Car Wraping & Coustomization",
        category : "carwrap",
        imgUrl : "/image/slaptop.png",
        description : "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Adipiscing commodo elit at imperdiet dui accumsan. Velit euismod in pellentesque massa placerat. Mauris vitae ultricies leo integer malesuada nunc vel risus. Dolor sit amet consectetur adipiscing.",
        link1 : "",
        link2 : "",
        gImg1 : "/image/scar.png", 
        gImg2 : "/image/scar.png", 
        gImg3 : "/image/scar.png", 
        gImg4 : "/image/scar.png", 

    },
    {
        id : 6,
        service : "Car Wraping & Coustomization",
        category : "carwrap",
        imgUrl : "/image/spdp.png",
        description : "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Adipiscing commodo elit at imperdiet dui accumsan. Velit euismod in pellentesque massa placerat. Mauris vitae ultricies leo integer malesuada nunc vel risus. Dolor sit amet consectetur adipiscing.",
        link1 : "",
        link2 : "",
        gImg1 : "/image/scar.png", 
        gImg2 : "/image/scar.png", 
        gImg3 : "/image/scar.png", 
        gImg4 : "/image/scar.png", 

    }, {
        id : 7,
        service : "Car Wraping & Coustomization",
        category : "carwrap",
        imgUrl : "/image/sap.png",
        description : "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Adipiscing commodo elit at imperdiet dui accumsan. Velit euismod in pellentesque massa placerat. Mauris vitae ultricies leo integer malesuada nunc vel risus. Dolor sit amet consectetur adipiscing.",
        link1 : "",
        link2 : "",
        gImg1 : "/image/scar.png", 
        gImg2 : "/image/scar.png", 
        gImg3 : "/image/scar.png", 
        gImg4 : "/image/scar.png", 

    }, {
        id : 8,
        service : "Car Wraping & Coustomization",
        category : "carwrap",
        imgUrl : "/image/srestore.png",
        description : "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Adipiscing commodo elit at imperdiet dui accumsan. Velit euismod in pellentesque massa placerat. Mauris vitae ultricies leo integer malesuada nunc vel risus. Dolor sit amet consectetur adipiscing.",
        link1 : "",
        link2 : "",
        gImg1 : "/image/scar.png", 
        gImg2 : "/image/scar.png", 
        gImg3 : "/image/scar.png", 
        gImg4 : "/image/scar.png", 

    }
]